### ISSUE TITLE
Nur ein Bild anzeigen

### ISSUE THREAD

**Issue by mistbock** [jensb89/Simple-Instagram-Photostream-with-PHP#1]
Moin moin,
besteht die Möglichkeit, dass lediglich das letzte Bild von Instagram angezeigt wird und nicht mehr? Viele Einstellungsmöglichkeiten gibt es ja nicht, oder?

Beste Grüße.

**Comment by jensb89** [comment]
Moin,
sry für die späte Antwort, Github hatte mir keine Benachrichtigung geschickt...
Nur ein Bild sollte relativ einfach gehen, indem man die URL abändert.
Auf https://www.instagram.com/developer/endpoints/users/#get_users_media_recent sind die verschiedenen Parameter angegeben.
Also einfach 
`$url="https://api.instagram.com/v1/users/{user-id}/media/recent?access_token=TOKEN&count=1";
`
Sollte das nicht gehen, kann man natürlich auch die for-Schleife entfernen und nur den letzten Eintrag zurückgeben...
